const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
document.querySelector('#year').textContent=new Date().getFullYear();
const floating=document.querySelector('.floating-quote');
const quote=document.querySelector('#quote');
function updateFloating(){const q=quote.getBoundingClientRect();floating.classList.toggle('visible',window.scrollY>window.innerHeight*.7&&(q.top>window.innerHeight*.85||q.bottom<0));}
window.addEventListener('scroll',updateFloating,{passive:true});updateFloating();
document.querySelectorAll('.product-options details').forEach(detail=>{detail.addEventListener('toggle',()=>{if(detail.open)document.querySelectorAll('.product-options details').forEach(other=>{if(other!==detail)other.open=false;});});});
const form=document.querySelector('#quote-form'),fields=[...form.querySelectorAll('fieldset')],statusBox=document.querySelector('#form-status');
function showStep(step,focus=true){fields.forEach((field,i)=>{field.hidden=i!==step-1;field.disabled=i===1&&step===1;});document.querySelector('#step-label').textContent=step===1?'Your packaging':'Your details';document.querySelector('#step-number').textContent=`Step ${step} of 2`;document.querySelector('.progress-line i').style.width=step===1?'50%':'100%';statusBox.hidden=true;if(focus)fields[step-1].querySelector('input,select')?.focus({preventScroll:true});}
document.querySelector('#next-step').addEventListener('click',()=>{if([...fields[0].querySelectorAll('input,select')].every(input=>input.reportValidity()))showStep(2);});
document.querySelector('#prev-step').addEventListener('click',()=>showStep(1));
form.addEventListener('keydown',event=>{if(event.key==='Enter'&&!fields[0].hidden&&event.target.tagName!=='TEXTAREA'){event.preventDefault();document.querySelector('#next-step').click();}});
document.querySelectorAll('.choose-box').forEach(button=>button.addEventListener('click',()=>{document.querySelector('#box-style').value=button.dataset.style;showStep(1,false);quote.scrollIntoView({behavior:reduced?'instant':'smooth',block:'start'});}));
function makeEmailLink(data){const lines=Object.entries(data).filter(([key,value])=>!key.startsWith('_')&&value).map(([key,value])=>`${key}: ${value}`);return 'mailto:alex@micro-printing.com?subject='+encodeURIComponent('Quality Container quote request')+'&body='+encodeURIComponent(lines.join('\n'));}
function showFormStatus(message,error=false,emailLink=null){statusBox.replaceChildren(document.createTextNode(message));statusBox.hidden=false;statusBox.dataset.error=String(error);if(emailLink){statusBox.append(document.createTextNode(' '));const link=document.createElement('a');link.href=emailLink;link.textContent='Email this request directly';statusBox.append(link);}statusBox.scrollIntoView({behavior:reduced?'instant':'smooth',block:'nearest'});}
form.addEventListener('submit',async event=>{event.preventDefault();if(!form.reportValidity())return;if(form.elements._honey.value)return;const data=Object.fromEntries(new FormData(form).entries()),button=document.querySelector('#submit-quote');button.disabled=true;button.textContent='Sending your request…';const controller=new AbortController(),timeout=setTimeout(()=>controller.abort(),20000);try{const response=await fetch('https://formsubmit.co/ajax/alex@micro-printing.com',{method:'POST',headers:{'Content-Type':'application/json',Accept:'application/json'},body:JSON.stringify(data),signal:controller.signal});const result=await response.json();if(!response.ok||!(result.success===true||result.success==='true')||/activat|confirm.*email/i.test(result.message||''))throw new Error('Submission was not confirmed.');showFormStatus('Your request has been submitted. Thank you for considering Quality Container. You can also email us if you have anything to add.');fields.forEach(field=>field.hidden=true);document.querySelector('#step-label').textContent='Thank you';document.querySelector('#step-number').textContent='Request submitted';form.reset();}catch(error){showFormStatus('We could not confirm your submission. Your details are still here—please try again or email your request to our team.',true,makeEmailLink(data));}finally{clearTimeout(timeout);button.disabled=false;button.textContent='Send quote request';}});
const modelContext=document.modelContext;
if(modelContext?.registerTool){const lifecycle=new AbortController();try{Promise.resolve(modelContext.registerTool({name:'prepare_quote_request',title:'Prepare a packaging quote',description:'Fill the packaging details in the visible quote form for review. This does not submit the form or send an email.',inputSchema:{type:'object',properties:{boxStyle:{type:'string',enum:['Shipping boxes','Custom sizes','Printed packaging','I need help choosing']},quantity:{type:'integer',minimum:1,maximum:100000000},length:{type:'number',minimum:.1},width:{type:'number',minimum:.1},depth:{type:'number',minimum:.1},units:{type:'string',enum:['inches','millimeters']}},required:['boxStyle','quantity'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute(input){const styles=['Shipping boxes','Custom sizes','Printed packaging','I need help choosing'];if(!input||!styles.includes(input.boxStyle)||!Number.isInteger(input.quantity)||input.quantity<1||input.quantity>100000000)throw new Error('Choose a supported box style and positive whole quantity.');for(const key of ['length','width','depth'])if(input[key]!==undefined&&(!Number.isFinite(input[key])||input[key]<.1))throw new Error('Dimensions must be positive numbers.');if(input.units!==undefined&&!['inches','millimeters'].includes(input.units))throw new Error('Unsupported units.');document.querySelector('#box-style').value=input.boxStyle;document.querySelector('#quantity').value=input.quantity;for(const key of ['length','width','depth'])document.querySelector('#'+key).value=input[key]??'';form.elements.Units.value=input.units??'inches';showStep(1,false);quote.scrollIntoView({behavior:'instant'});return {prepared:true,submitted:false,boxStyle:input.boxStyle,quantity:input.quantity};}},{signal:lifecycle.signal})).catch(()=>{});}catch(error){}window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});}

document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener('click',event=>{const id=link.getAttribute('href').slice(1),target=id?document.getElementById(id):document.body;if(target){event.preventDefault();target.scrollIntoView({behavior:reduced?'instant':'smooth',block:'start'});}}));
