(() => {
  const clamp=(v,min=0,max=1)=>Math.min(max,Math.max(min,v));
  const smooth=v=>v*v*(3-2*v);
  const stage=document.querySelector('.hero-story'),canvas=document.querySelector('#box-canvas'),ctx=canvas.getContext('2d',{alpha:false});
  const poster=document.querySelector('.hero-poster'),title=document.querySelector('.hero-title-wrap'),caption=document.querySelector('.hero-caption'),openButton=document.querySelector('.open-experience'),copyOpen=document.querySelector('.scene-copy-open'),copyInside=document.querySelector('.scene-copy-inside');
  const toggle=document.querySelector('#motion-toggle'),header=document.querySelector('.site-header'),progress=document.querySelector('.chapter-progress i'),chapter=document.querySelector('#chapter-label');
  const anatomy=document.querySelector('.anatomy-story'),anatomyImage=document.querySelector('.anatomy-art>img'),dieline=document.querySelector('.dieline'),material=document.querySelector('.material-section'),materialImage=material.querySelector('img'),intro=document.querySelector('.intro-section');
  const motionQuery=matchMedia('(prefers-reduced-motion: reduce)');let paused=motionQuery.matches,frame=0,scrollProgress=0,introStart=0,userScrolled=false,lastTime=0,rendered=-1,w=0,h=0,dpr=1,pointerX=0,pointerY=0,px=0,py=0,raf=0;
  const images=new Array(121),loaded=new Set();
  function resize(){w=canvas.clientWidth;h=canvas.clientHeight;dpr=Math.min(devicePixelRatio||1,1.6);canvas.width=Math.round(w*dpr);canvas.height=Math.round(h*dpr);rendered=-1;requestTick();}
  function nearest(index){if(images[index])return index;for(let n=1;n<121;n++){if(images[index-n])return index-n;if(images[index+n])return index+n;}return -1;}
  function render(index,p){const available=nearest(index);if(available<0)return;const image=images[available],mobile=w<760,zoom=1+smooth(clamp((p-.65)/.27))*2.8;const base=mobile?Math.max(w/1.12,h*.9):Math.max(w/1.78,h*.96);const ih=base*(mobile?.79:.9)*zoom,iw=ih*16/9;const cx=w*(mobile?.52:.5),cy=h*(mobile?.55:.58);const x=cx-iw*.63+px*(1-p)*10,y=cy-ih*.53+py*(1-p)*6;ctx.setTransform(dpr,0,0,dpr,0,0);ctx.fillStyle='#090a08';ctx.fillRect(0,0,w,h);ctx.drawImage(image,x,y,iw,ih);const curtain=smooth(clamp((p-.84)/.16));if(curtain>0){ctx.fillStyle=`rgba(9,10,8,${curtain*.93})`;ctx.fillRect(0,0,w,h);}canvas.dataset.frame=String(available);canvas.dataset.progress=p.toFixed(3);rendered=available;poster.style.opacity='0';}
  function paint(time){raf=0;const delta=Math.min((time-lastTime)||16,50);lastTime=time;const rect=stage.getBoundingClientRect();scrollProgress=clamp(-rect.top/Math.max(1,stage.offsetHeight-innerHeight));if(scrollProgress>.008)userScrolled=true;let target=clamp(scrollProgress/.67)*120;let introActive=false;if(!paused&&!userScrolled&&loaded.size>12){if(!introStart)introStart=time;const t=(time-introStart)/1000;if(t<5){target=Math.sin(Math.PI*clamp(t/5))*48;introActive=true;}}
    if(paused)target=motionQuery.matches?0:frame;frame+= (target-frame)*(1-Math.exp(-delta/80));if(Math.abs(target-frame)<.03)frame=target;px+=(pointerX-px)*.09;py+=(pointerY-py)*.09;const p=motionQuery.matches?0:scrollProgress;
    if((!paused&&rect.bottom>0&&rect.top<innerHeight)||rendered<0)render(Math.round(frame),p);
    const leave=smooth(clamp(p/.24));title.style.opacity=String(1-leave);title.style.transform=`translateY(${-leave*110}px) scale(${1+leave*.16})`;caption.style.opacity=String(1-clamp(p/.14));caption.style.transform=`translateY(${leave*30}px)`;openButton.style.opacity=String(1-clamp(p/.1));openButton.style.pointerEvents=p>.1?'none':'auto';
    const enter=smooth(clamp((p-.25)/.12)),exit=smooth(clamp((p-.56)/.1));copyOpen.style.opacity=String(enter*(1-exit));copyOpen.style.transform=`translateY(${(1-enter)*45-exit*45}px)`;const inside=smooth(clamp((p-.84)/.1));copyInside.style.opacity=String(inside);copyInside.style.transform=`scale(${.88+inside*.12})`;progress.style.width=`${p*100}%`;chapter.textContent=p<.3?'01 — The possibility':p<.7?'02 — The opening':'03 — A closer look';
    header.classList.toggle('scrolled',scrollY>innerHeight*.8);if(!paused){const ap=clamp(-anatomy.getBoundingClientRect().top/Math.max(1,anatomy.offsetHeight-innerHeight));const af=smooth(clamp((ap-.15)/.58));anatomyImage.style.opacity=1-af;anatomyImage.style.transform=`perspective(1200px) rotateZ(${-af*12}deg) scale(${1-af*.4})`;dieline.style.opacity=af;dieline.style.transform=`scale(${.68+af*.32}) rotate(${-8+af*8}deg)`;const mr=material.getBoundingClientRect();materialImage.style.transform=`translateY(${clamp((innerHeight-mr.top)/(innerHeight+mr.height)) * 90-45}px) scale(1.08)`;const ir=intro.getBoundingClientRect();intro.style.setProperty('--read-progress',`${clamp((innerHeight-ir.top)/(innerHeight*.9))*100}%`);}
    if(introActive||Math.abs(target-frame)>.03||Math.abs(px-pointerX)>.005||Math.abs(py-pointerY)>.005)requestTick();
  }
  function requestTick(){if(!raf)raf=requestAnimationFrame(paint);}
  async function load(index){const image=new Image();image.decoding='async';image.src=`./assets/box-sequence/frame-${String(index+1).padStart(3,'0')}.jpg`;try{await image.decode();images[index]=image;loaded.add(index);requestTick();}catch{canvas.dataset.loadError='true';}}
  async function loadSequence(){await load(0);if(motionQuery.matches)return;const priorities=[120,60,30,90,15,45,75,105,...Array.from({length:121},(_,i)=>i)];const order=[...new Set(priorities)].filter(i=>i!==0);let next=0;await Promise.all(Array.from({length:8},async()=>{while(next<order.length)await load(order[next++]);}));canvas.dataset.loaded=String(loaded.size);}
  openButton.addEventListener('click',()=>{userScrolled=true;window.scrollTo({top:stage.offsetTop+(stage.offsetHeight-innerHeight)*.57,behavior:'smooth'});});
  toggle.textContent=paused?'Motion off':'Pause motion';toggle.setAttribute('aria-pressed',String(paused));toggle.addEventListener('click',()=>{paused=!paused;toggle.textContent=paused?'Resume motion':'Pause motion';toggle.setAttribute('aria-pressed',String(paused));requestTick();});
  motionQuery.addEventListener('change',event=>{paused=event.matches;toggle.textContent=paused?'Motion off':'Pause motion';toggle.setAttribute('aria-pressed',String(paused));if(!paused&&loaded.size<2)loadSequence();resize();});
  window.addEventListener('scroll',requestTick,{passive:true});window.addEventListener('resize',resize);document.addEventListener('visibilitychange',()=>{if(!document.hidden)requestTick();});
  stage.addEventListener('pointermove',event=>{if(event.pointerType==='mouse'&&!paused){pointerX=event.clientX/innerWidth-.5;pointerY=event.clientY/innerHeight-.5;requestTick();}});stage.addEventListener('pointerleave',()=>{pointerX=pointerY=0;requestTick();});
  document.querySelectorAll('.product-options details').forEach((detail,index)=>detail.addEventListener('toggle',()=>{if(detail.open&&!paused){document.querySelector('.product-visual img').style.transform=`scale(${1.05+index*.12}) rotate(${index===1?-6:index===2?5:0}deg)`;}}));
  resize();loadSequence();
})();
